// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.unutma.unutma.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object UnutmaApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class CardDto (
  val id: String,
  val category: String,
  val title: String,
  val sourceLabel: String,
  val sourcePackage: String,
  val dueAt: Long? = null,
  val amount: String? = null,
  val currency: String? = null,
  val status: String,
  val confidence: Double,
  val createdAt: Long,
  val completedAt: Long? = null,
  val reminderOffsets: List<Long>,
  val snoozedUntil: Long? = null,
  val parserVersion: Long,
  val note: String? = null,
  val sourceMessage: String? = null,
  val revision: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CardDto {
      val id = pigeonVar_list[0] as String
      val category = pigeonVar_list[1] as String
      val title = pigeonVar_list[2] as String
      val sourceLabel = pigeonVar_list[3] as String
      val sourcePackage = pigeonVar_list[4] as String
      val dueAt = pigeonVar_list[5] as Long?
      val amount = pigeonVar_list[6] as String?
      val currency = pigeonVar_list[7] as String?
      val status = pigeonVar_list[8] as String
      val confidence = pigeonVar_list[9] as Double
      val createdAt = pigeonVar_list[10] as Long
      val completedAt = pigeonVar_list[11] as Long?
      val reminderOffsets = pigeonVar_list[12] as List<Long>
      val snoozedUntil = pigeonVar_list[13] as Long?
      val parserVersion = pigeonVar_list[14] as Long
      val note = pigeonVar_list[15] as String?
      val sourceMessage = pigeonVar_list[16] as String?
      val revision = pigeonVar_list[17] as Long
      return CardDto(id, category, title, sourceLabel, sourcePackage, dueAt, amount, currency, status, confidence, createdAt, completedAt, reminderOffsets, snoozedUntil, parserVersion, note, sourceMessage, revision)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      category,
      title,
      sourceLabel,
      sourcePackage,
      dueAt,
      amount,
      currency,
      status,
      confidence,
      createdAt,
      completedAt,
      reminderOffsets,
      snoozedUntil,
      parserVersion,
      note,
      sourceMessage,
      revision,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CardDto
    return UnutmaApiPigeonUtils.deepEquals(this.id, other.id) && UnutmaApiPigeonUtils.deepEquals(this.category, other.category) && UnutmaApiPigeonUtils.deepEquals(this.title, other.title) && UnutmaApiPigeonUtils.deepEquals(this.sourceLabel, other.sourceLabel) && UnutmaApiPigeonUtils.deepEquals(this.sourcePackage, other.sourcePackage) && UnutmaApiPigeonUtils.deepEquals(this.dueAt, other.dueAt) && UnutmaApiPigeonUtils.deepEquals(this.amount, other.amount) && UnutmaApiPigeonUtils.deepEquals(this.currency, other.currency) && UnutmaApiPigeonUtils.deepEquals(this.status, other.status) && UnutmaApiPigeonUtils.deepEquals(this.confidence, other.confidence) && UnutmaApiPigeonUtils.deepEquals(this.createdAt, other.createdAt) && UnutmaApiPigeonUtils.deepEquals(this.completedAt, other.completedAt) && UnutmaApiPigeonUtils.deepEquals(this.reminderOffsets, other.reminderOffsets) && UnutmaApiPigeonUtils.deepEquals(this.snoozedUntil, other.snoozedUntil) && UnutmaApiPigeonUtils.deepEquals(this.parserVersion, other.parserVersion) && UnutmaApiPigeonUtils.deepEquals(this.note, other.note) && UnutmaApiPigeonUtils.deepEquals(this.sourceMessage, other.sourceMessage) && UnutmaApiPigeonUtils.deepEquals(this.revision, other.revision)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.id)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.category)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.title)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.sourceLabel)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.sourcePackage)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.dueAt)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.amount)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.currency)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.status)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.confidence)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.createdAt)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.completedAt)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.reminderOffsets)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.snoozedUntil)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.parserVersion)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.note)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.sourceMessage)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.revision)
    return result
  }
  override fun toString(): String {
    return "CardDto(id=$id, category=$category, title=$title, sourceLabel=$sourceLabel, sourcePackage=$sourcePackage, dueAt=$dueAt, amount=$amount, currency=$currency, status=$status, confidence=$confidence, createdAt=$createdAt, completedAt=$completedAt, reminderOffsets=$reminderOffsets, snoozedUntil=$snoozedUntil, parserVersion=$parserVersion, note=$note, sourceMessage=$sourceMessage, revision=$revision)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreferencesDto (
  val onboarded: Boolean,
  val language: String,
  val theme: String,
  val reminderMinutes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreferencesDto {
      val onboarded = pigeonVar_list[0] as Boolean
      val language = pigeonVar_list[1] as String
      val theme = pigeonVar_list[2] as String
      val reminderMinutes = pigeonVar_list[3] as Long
      return PreferencesDto(onboarded, language, theme, reminderMinutes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      onboarded,
      language,
      theme,
      reminderMinutes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PreferencesDto
    return UnutmaApiPigeonUtils.deepEquals(this.onboarded, other.onboarded) && UnutmaApiPigeonUtils.deepEquals(this.language, other.language) && UnutmaApiPigeonUtils.deepEquals(this.theme, other.theme) && UnutmaApiPigeonUtils.deepEquals(this.reminderMinutes, other.reminderMinutes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.onboarded)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.language)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.theme)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.reminderMinutes)
    return result
  }
  override fun toString(): String {
    return "PreferencesDto(onboarded=$onboarded, language=$language, theme=$theme, reminderMinutes=$reminderMinutes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AccessDto (
  val listenerEnabled: Boolean,
  val remindersEnabled: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AccessDto {
      val listenerEnabled = pigeonVar_list[0] as Boolean
      val remindersEnabled = pigeonVar_list[1] as Boolean
      return AccessDto(listenerEnabled, remindersEnabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      listenerEnabled,
      remindersEnabled,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AccessDto
    return UnutmaApiPigeonUtils.deepEquals(this.listenerEnabled, other.listenerEnabled) && UnutmaApiPigeonUtils.deepEquals(this.remindersEnabled, other.remindersEnabled)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.listenerEnabled)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.remindersEnabled)
    return result
  }
  override fun toString(): String {
    return "AccessDto(listenerEnabled=$listenerEnabled, remindersEnabled=$remindersEnabled)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SourceDto (
  val packageName: String,
  val label: String,
  val ignored: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SourceDto {
      val packageName = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val ignored = pigeonVar_list[2] as Boolean
      return SourceDto(packageName, label, ignored)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      label,
      ignored,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SourceDto
    return UnutmaApiPigeonUtils.deepEquals(this.packageName, other.packageName) && UnutmaApiPigeonUtils.deepEquals(this.label, other.label) && UnutmaApiPigeonUtils.deepEquals(this.ignored, other.ignored)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.label)
    result = 31 * result + UnutmaApiPigeonUtils.deepHash(this.ignored)
    return result
  }
  override fun toString(): String {
    return "SourceDto(packageName=$packageName, label=$label, ignored=$ignored)"
  }
}
private open class UnutmaApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CardDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreferencesDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AccessDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SourceDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CardDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PreferencesDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AccessDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SourceDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UnutmaApi {
  suspend fun getCards(): List<CardDto>
  suspend fun saveCard(card: CardDto): CardDto
  suspend fun transition(id: String, action: String, revision: Long)
  suspend fun clearSourceMessage(id: String)
  suspend fun deleteAllData()
  suspend fun getSources(): List<SourceDto>
  suspend fun setSourceIgnored(packageName: String, ignored: Boolean)
  suspend fun getAccess(): AccessDto
  fun openNotificationAccess()
  fun requestReminderPermission()
  fun getPreferences(): PreferencesDto
  fun setPreferences(preferences: PreferencesDto)
  suspend fun reconcile()
  fun takeOpenedCard(): String?
  fun takeSharedText(): String?
  suspend fun importSharedText(text: String): String?

  companion object {
    /** The codec used by UnutmaApi. */
    val codec: MessageCodec<Any?> by lazy {
      UnutmaApiPigeonCodec()
    }
    /** Sets up an instance of `UnutmaApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UnutmaApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.getCards$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getCards())
              } catch (exception: Throwable) {
                UnutmaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.saveCard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cardArg = args[0] as CardDto
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.saveCard(cardArg))
              } catch (exception: Throwable) {
                UnutmaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.transition$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val actionArg = args[1] as String
            val revisionArg = args[2] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.transition(idArg, actionArg, revisionArg)
                listOf(null)
              } catch (exception: Throwable) {
                UnutmaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.clearSourceMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.clearSourceMessage(idArg)
                listOf(null)
              } catch (exception: Throwable) {
                UnutmaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.deleteAllData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.deleteAllData()
                listOf(null)
              } catch (exception: Throwable) {
                UnutmaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.getSources$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getSources())
              } catch (exception: Throwable) {
                UnutmaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.setSourceIgnored$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val ignoredArg = args[1] as Boolean
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setSourceIgnored(packageNameArg, ignoredArg)
                listOf(null)
              } catch (exception: Throwable) {
                UnutmaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.getAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getAccess())
              } catch (exception: Throwable) {
                UnutmaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.openNotificationAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openNotificationAccess()
              listOf(null)
            } catch (exception: Throwable) {
              UnutmaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.requestReminderPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestReminderPermission()
              listOf(null)
            } catch (exception: Throwable) {
              UnutmaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.getPreferences$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPreferences())
            } catch (exception: Throwable) {
              UnutmaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.setPreferences$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val preferencesArg = args[0] as PreferencesDto
            val wrapped: List<Any?> = try {
              api.setPreferences(preferencesArg)
              listOf(null)
            } catch (exception: Throwable) {
              UnutmaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.reconcile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.reconcile()
                listOf(null)
              } catch (exception: Throwable) {
                UnutmaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.takeOpenedCard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.takeOpenedCard())
            } catch (exception: Throwable) {
              UnutmaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.takeSharedText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.takeSharedText())
            } catch (exception: Throwable) {
              UnutmaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unutma.UnutmaApi.importSharedText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.importSharedText(textArg))
              } catch (exception: Throwable) {
                UnutmaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class UnutmaEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by UnutmaEvents. */
    val codec: MessageCodec<Any?> by lazy {
      UnutmaApiPigeonCodec()
    }
  }
  suspend fun cardsChanged()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.unutma.UnutmaEvents.cardsChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(UnutmaApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun sharedTextReceived()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.unutma.UnutmaEvents.sharedTextReceived$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(UnutmaApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
