// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class CardDto {
  CardDto({
    required this.id,
    required this.category,
    required this.title,
    required this.sourceLabel,
    required this.sourcePackage,
    this.dueAt,
    this.amount,
    this.currency,
    required this.status,
    required this.confidence,
    required this.createdAt,
    this.completedAt,
    required this.reminderOffsets,
    this.snoozedUntil,
    required this.parserVersion,
    this.note,
    this.sourceMessage,
    required this.revision,
  });

  String id;

  String category;

  String title;

  String sourceLabel;

  String sourcePackage;

  int? dueAt;

  String? amount;

  String? currency;

  String status;

  double confidence;

  int createdAt;

  int? completedAt;

  List<int> reminderOffsets;

  int? snoozedUntil;

  int parserVersion;

  String? note;

  String? sourceMessage;

  int revision;

  List<Object?> _toList() {
    return <Object?>[
      id,
      category,
      title,
      sourceLabel,
      sourcePackage,
      dueAt,
      amount,
      currency,
      status,
      confidence,
      createdAt,
      completedAt,
      reminderOffsets,
      snoozedUntil,
      parserVersion,
      note,
      sourceMessage,
      revision,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CardDto decode(Object result) {
    result as List<Object?>;
    return CardDto(
      id: result[0]! as String,
      category: result[1]! as String,
      title: result[2]! as String,
      sourceLabel: result[3]! as String,
      sourcePackage: result[4]! as String,
      dueAt: result[5] as int?,
      amount: result[6] as String?,
      currency: result[7] as String?,
      status: result[8]! as String,
      confidence: result[9]! as double,
      createdAt: result[10]! as int,
      completedAt: result[11] as int?,
      reminderOffsets: (result[12]! as List<Object?>).cast<int>(),
      snoozedUntil: result[13] as int?,
      parserVersion: result[14]! as int,
      note: result[15] as String?,
      sourceMessage: result[16] as String?,
      revision: result[17]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CardDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(category, other.category) &&
        _deepEquals(title, other.title) &&
        _deepEquals(sourceLabel, other.sourceLabel) &&
        _deepEquals(sourcePackage, other.sourcePackage) &&
        _deepEquals(dueAt, other.dueAt) &&
        _deepEquals(amount, other.amount) &&
        _deepEquals(currency, other.currency) &&
        _deepEquals(status, other.status) &&
        _deepEquals(confidence, other.confidence) &&
        _deepEquals(createdAt, other.createdAt) &&
        _deepEquals(completedAt, other.completedAt) &&
        _deepEquals(reminderOffsets, other.reminderOffsets) &&
        _deepEquals(snoozedUntil, other.snoozedUntil) &&
        _deepEquals(parserVersion, other.parserVersion) &&
        _deepEquals(note, other.note) &&
        _deepEquals(sourceMessage, other.sourceMessage) &&
        _deepEquals(revision, other.revision);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CardDto(id: $id, category: $category, title: $title, sourceLabel: $sourceLabel, sourcePackage: $sourcePackage, dueAt: $dueAt, amount: $amount, currency: $currency, status: $status, confidence: $confidence, createdAt: $createdAt, completedAt: $completedAt, reminderOffsets: $reminderOffsets, snoozedUntil: $snoozedUntil, parserVersion: $parserVersion, note: $note, sourceMessage: $sourceMessage, revision: $revision)';
  }
}

class PreferencesDto {
  PreferencesDto({
    required this.onboarded,
    required this.language,
    required this.theme,
    required this.reminderMinutes,
  });

  bool onboarded;

  String language;

  String theme;

  int reminderMinutes;

  List<Object?> _toList() {
    return <Object?>[onboarded, language, theme, reminderMinutes];
  }

  Object encode() {
    return _toList();
  }

  static PreferencesDto decode(Object result) {
    result as List<Object?>;
    return PreferencesDto(
      onboarded: result[0]! as bool,
      language: result[1]! as String,
      theme: result[2]! as String,
      reminderMinutes: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreferencesDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(onboarded, other.onboarded) &&
        _deepEquals(language, other.language) &&
        _deepEquals(theme, other.theme) &&
        _deepEquals(reminderMinutes, other.reminderMinutes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PreferencesDto(onboarded: $onboarded, language: $language, theme: $theme, reminderMinutes: $reminderMinutes)';
  }
}

class AccessDto {
  AccessDto({required this.listenerEnabled, required this.remindersEnabled});

  bool listenerEnabled;

  bool remindersEnabled;

  List<Object?> _toList() {
    return <Object?>[listenerEnabled, remindersEnabled];
  }

  Object encode() {
    return _toList();
  }

  static AccessDto decode(Object result) {
    result as List<Object?>;
    return AccessDto(
      listenerEnabled: result[0]! as bool,
      remindersEnabled: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AccessDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(listenerEnabled, other.listenerEnabled) &&
        _deepEquals(remindersEnabled, other.remindersEnabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AccessDto(listenerEnabled: $listenerEnabled, remindersEnabled: $remindersEnabled)';
  }
}

class SourceDto {
  SourceDto({
    required this.packageName,
    required this.label,
    required this.ignored,
  });

  String packageName;

  String label;

  bool ignored;

  List<Object?> _toList() {
    return <Object?>[packageName, label, ignored];
  }

  Object encode() {
    return _toList();
  }

  static SourceDto decode(Object result) {
    result as List<Object?>;
    return SourceDto(
      packageName: result[0]! as String,
      label: result[1]! as String,
      ignored: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SourceDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packageName, other.packageName) &&
        _deepEquals(label, other.label) &&
        _deepEquals(ignored, other.ignored);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SourceDto(packageName: $packageName, label: $label, ignored: $ignored)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CardDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PreferencesDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is AccessDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is SourceDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return CardDto.decode(readValue(buffer)!);
      case 130:
        return PreferencesDto.decode(readValue(buffer)!);
      case 131:
        return AccessDto.decode(readValue(buffer)!);
      case 132:
        return SourceDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class UnutmaApi {
  /// Constructor for [UnutmaApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  UnutmaApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<CardDto>> getCards() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.getCards$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<CardDto>();
  }

  Future<CardDto> saveCard(CardDto card) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.saveCard$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[card],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CardDto;
  }

  Future<void> transition(String id, String action, int revision) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.transition$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id, action, revision],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> clearSourceMessage(String id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.clearSourceMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> deleteAllData() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.deleteAllData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<SourceDto>> getSources() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.getSources$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<SourceDto>();
  }

  Future<void> setSourceIgnored(String packageName, bool ignored) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.setSourceIgnored$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[packageName, ignored],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<AccessDto> getAccess() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.getAccess$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AccessDto;
  }

  Future<void> openNotificationAccess() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.openNotificationAccess$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> requestReminderPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.requestReminderPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<PreferencesDto> getPreferences() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.getPreferences$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PreferencesDto;
  }

  Future<void> setPreferences(PreferencesDto preferences) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.setPreferences$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[preferences],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> reconcile() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.reconcile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String?> takeOpenedCard() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.takeOpenedCard$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<String?> takeSharedText() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.takeSharedText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<String?> importSharedText(String text) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unutma.UnutmaApi.importSharedText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[text],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }
}

abstract class UnutmaEvents {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void cardsChanged();

  void sharedTextReceived();

  static void setUp(
    UnutmaEvents? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.unutma.UnutmaEvents.cardsChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.cardsChanged();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.unutma.UnutmaEvents.sharedTextReceived$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.sharedTextReceived();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
